[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[etherscan]
# Base Sepolia (chain ID 84532)
base-sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

